### ISSUE TITLE
Cannot read property 'policy' of undefined

### ISSUE THREAD

**Issue by devotox** [rwjblue/ember-cli-content-security-policy#124]
This happens because of this new addition
`https://github.com/rwjblue/ember-cli-content-security-policy/blame/master/index.js#L133`

**Comment by jelhan** [comment]
Thanks a lot for reporting!

Configuration for tests is only calculated if build contains tests (`app.tests  === true`). Otherwise `_configForTests` is not set: https://github.com/rwjblue/ember-cli-content-security-policy/blob/6a19a8ddb2fc8f7e032bfe370f52b23850ac6313/index.js#L79-L94

Seem like I also missed to document `_configForTest` and `_policyStringForTest` as it's done for `_config` and `_policyString`. Might have made debugging easier for other ones.

If I didn't missed something this is only be triggered if using development server for a build that does not contain tests. I guess you are running something like `ember serve --environment production`?

**Comment by devotox** [comment]
Yes I think its something like that. I built the production build and then ran it with the dev server
