### ISSUE TITLE
Different development hostname

### ISSUE THREAD

**Issue by tonycoco** [rwjblue/ember-cli-content-security-policy#18]
I use a hostname, something like:

`http://portfolio.dev`

for some of my projects. Could we make https://github.com/rwjblue/ember-cli-content-security-policy/blob/master/index.js#L38 work with a config'ed var instead of hard-coding those 2 options?

I'll take a stab at it if I get some time.

**Comment by jfelchner** [comment]
Yeah I agree.  Even using something like `lvh.me` blows up the console.

**Comment by grempe** [comment]
Where would one add the options.host headerConfig override that @rwjblue mentioned above (forgive an ember.js newbie)?

Also, could 127.0.0.1 be added to the list in addition to 0.0.0.0 and localhost?  Trying to visit a 0.0.0.0 url on my OS X Yosemite machine, in Chrome with DuckDuckGo as the search engine default takes me to a duckduckgo search page for 0.0.0.0, and not the localhost.  In safari it works fine though.  And 127.0.0.1 has been ingrained in my brain as the local address for too many years to give up on it now.

+1 for an easy and documented way to override this in ember-cli config.

**Comment by timohofmeijer** [comment]
@grempe, my comment was a suggestion for letting ember-cli automatically grant permission when running your dev server from a custom hostname. This is not something you want to tweak yourself since it'll be overwritten anytime you fetch dependencies. Just add your [custom host](http://www.ember-cli.com/#runtime-configuration) to `connect-src` and `script-src` in the `contentSecurityPolicy` declaration in `config/environment.js`.

This works just fine except it also publishes the policy to production builds.

https://github.com/rwjblue/ember-cli-content-security-policy

**Comment by akshayrawat** [comment]
+1. Trying to figure out the same issue.

**Comment by Leeft** [comment]
Essentially repeating and summarizing what was stated above already:

Right now it is assumed that the ember server is running on localhost (it seems that can be changed through `--host` which ends up in `config.host` as below), but the liveReload server in particular is always assumed to be a hardcoded `localhost` or `0.0.0.0`:

```
      if (options.liveReload) {
        ['localhost', '0.0.0.0'].forEach(function(host) {
          headerConfig['connect-src'] = headerConfig['connect-src'] + ' ws://' + host + ':' + options.liveReloadPort;
          headerConfig['script-src'] = headerConfig['script-src'] + ' ' + host + ':' + options.liveReloadPort;
        });
      }
```

I run my ember server on a VM with `ember serve --host 192.168.1.37`, and access it through that IP. I always get a lot of CSP warnings, and it's a little bit tedious to add my VM's IP to each Ember app I create for just that reason.

As a quick hack, this works to get rid of these CSP warnings:

```
        ['localhost', '0.0.0.0', options.host].forEach(function(host) {
```

I'm not entirely sure what the best fix would be though. I don't see a need to keep `localhost` and `0.0.0.0` around rather than just `options.host`, but I might be missing something. Also, if they are combined like this then it should probably use http://emberjs.com/api/classes/Ember.Array.html#method_uniq if that's available rather than reinventing the code?

**Comment by jhr007** [comment]
I go my development url to work by adding the hostname from Express's request object. `req.hostname`

I think using `req.hostname` leaves no need for `localhost` or `0.0.0.0` , but I haven't looked into `ember-cli-content-security-policy` 's whole intent or the surrounding code.  

On the following line, I added `req.hostname`.
https://github.com/rwjblue/ember-cli-content-security-policy/blob/master/index.js#L38
```
['localhost', '0.0.0.0', req.hostname].forEach(function(host) {

```

**Comment by sandstrom** [comment]
+1 here.

I think the correct place to handle this is within ember-cli (live-reloading suffer similar issues), and making that value available to all addons (including this one).

**Comment by patrickberkeley** [comment]
Using wildcards fixed this issue for me. E.g.,

```js
  ENV.contentSecurityPolicy = {
    'script-src': "'self' http://*.custom.domain:*/livereload.js",
    'connect-src': "'self' ws://*.custom.domain:*/livereload"
  };
```

Where `custom.domain` should be replaced with whatever domain you're accessing your ember app on locally.

**Comment by abobwhite** [comment]
@patrickberkeley Thanks for your solution. Works great.
