### ISSUE TITLE
options should not come from config/env, rather the brocfil. These are build-server concerns not run-time concerns

### ISSUE THREAD

**Issue by stefanpenner** [rwjblue/ember-cli-content-security-policy#30]

**Comment by rwjblue** [comment]
False, these options cannot come from the `Brocfile.js` since we need them in the server middleware which does not have access to Brocfile configuration.

**Comment by rwjblue** [comment]
But the fundamental problem is that runtime config is *not* the same as build time or server side configuration.  This is the conundrum of the configuration work that is next on the plate...

**Comment by stefanpenner** [comment]
then they need to reside in something before the brocfile, but they cannot live in the config/env that is for UI client-side concerns.

**Comment by rwjblue** [comment]
I definitely agree that this and many other config options do not belong in runtime config. 

But there is little value in changing this twice. We need to fix configuration in general, and this will just be taken care of for us. I'll try to double down on this config work in the next few days to get to an RFC, and then we can start implementation once we have basic agreement.

**Comment by stefanpenner** [comment]
Awesome. I've been using this and other problems to fuel my problem solving constraint solver on this problem. That way I can review your rfc's with good context

**Comment by jelhan** [comment]
@sandstrom This one is next on my priority list as it should land in the same release as #94 in my opinion. It's about moving the configuration from `config/environment.js` to `ember-cli-build.js`. Just want to make sure that you are on the same boat.

**Comment by sandstrom** [comment]
@jelhan Sounds good!

This thread is pretty old, is there a way to access the `Brocfile.js` (old name) / `ember-cli-build.js` config from `serverMiddleware` and `contentFor` these days? (the drawback mentioned above)

**Comment by jelhan** [comment]
> This thread is pretty old, is there a way to access the `Brocfile.js` (old name) / `ember-cli-build.js` config from `serverMiddleware` and `contentFor` these days?

`this._findHost(this).options[CONFIG_KEY]` is working fine in both hooks but is private API. It's supported since Ember CLI 2.7 so would need a polyfill to support Ember CLI < 2.7. This is inspired by Ember Bootstrap. It seems to work fine there (even so it's used in `included` hook only).

`ember-cli-uglify` and `ember-fontawesome` are using `options` property of `app` passed to `included` hook to get the build time config. Accordingly to quick checks `included` hook is called before `serverMiddleware` and `contentFor` so getting the options there and storing it locally should also be fine. I'm not sure if this execution order is considered public API.

**Comment by sandstrom** [comment]
@jelhan Great research! Let's follow the structure used by `ember-cli-uglify` and use the included hook to store locally.

If you want, you can add a comment mentioning the `this._findHost(this).options[CONFIG_KEY]` trick and that we'd like to use something like that should it become a public API in the future.
