### ISSUE TITLE
still getting CSP violation report-only warning even if contentSecurityPolicy is overridden

### ISSUE THREAD

**Issue by hotterd** [rwjblue/ember-cli-content-security-policy#46]
Hi,

I'm using ember-cli to receive data from REST API backed by express at http://localhost:3000". 
I have my env settings as follows
```javascript
    contentSecurityPolicy: {
      'connect-src' : "'self' http://localhost:3000"
    }
```
While I can get the data and render it without problem, I'm still seeing a report-only warning as below:
```
[Report Only] Refused to load plugin data from '' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'object-src' was not explicitly set, so 'default-src' is used as a fallback.
```
This warning keeps bumping up until I override default-src from 'none' to 'self' in addition to the 'connect-src':
```
'default-src': "'self'",
...
```
Is this the expected behavior?

Here's the versions:
```
[Debug] DEBUG: ------------------------------- (vendor.js, line 15931)
[Debug] DEBUG: Ember      : 1.13.3 (vendor.js, line 15931)
[Debug] DEBUG: Ember Data : 1.13.5 (vendor.js, line 15931)
[Debug] DEBUG: jQuery     : 1.11.3 (vendor.js, line 15931)
[Debug] DEBUG: ------------------------------- (vendor.js, line 15931)
```
I'm using safari to test the page, it this matters.

Thanks,
Gan

**Comment by sandstrom** [comment]
@hotterd 99% sure this is not an issue with this addon.

CSP is very useful, but somewhat complicated. My guess is that something is triggering the `object-src` clause that you've overlooked. Possibly a browser-plugin. This is a pretty good intro, if you haven't read it: http://www.html5rocks.com/en/tutorials/security/content-security-policy/

I think it's safe to close this issue, since the problem is outside the scope of this addon.

**Comment by hotterd** [comment]
@sandstrom thanks for the explanation, I'll look into it.
